# Generated by Django 4.1 on 2022-12-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(max_length=100)),
                ('especialidad_estudio', models.CharField(max_length=50)),
                ('cantidad_estudios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=50)),
                ('apellido_familiar', models.CharField(max_length=50)),
                ('email_familiar', models.EmailField(max_length=254)),
                ('edad_familiar', models.IntegerField()),
                ('nacimiento_familiar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=50)),
                ('edad_mascota', models.IntegerField()),
            ],
        ),
    ]
